import { Router, type IRouter } from "express";
import healthRouter    from "./health.js";
import authRouter      from "./auth.js";
import ridesRouter     from "./rides.js";
import driversRouter   from "./drivers.js";
import dispatcherRouter from "./dispatcher.js";
import messagesRouter  from "./messages.js";
import tariffsRouter   from "./tariffs.js";
import callsRouter     from "./calls.js";
import analyticsRouter from "./analytics.js";
import paymentsRouter  from "./payments.js";
import routesMgmtRouter from "./routesManagement.js";
import routeOptionsRouter from "./routeOptions.js";
import branchesRouter  from "./branches.js";
import citiesRouter    from "./cities.js";
import addressesRouter from "./addresses.js";
import staffRouter     from "./staff.js";
import settingsRouter  from "./settings.js";
import activityLogsRouter from "./activityLogs.js";
import chatRouter      from "./chat.js";
import districtsRouter from "./districts.js";
import marketplaceRouter from "./marketplace.js";
import metricsRouter from "./metrics.js";
import rbacRouter from "./rbac.js";
import driverGroupsRouter from "./driver-groups.js";
import photoControlRouter from "./photo-control.js";
import audioFilesRouter from "./audio-files.js";
import systemRouter from "./system.js";
import debugRouter from "./debug.js";
import apkRouter from "./apk.js";
import newsRouter from "./news.js";
import pushNotificationsRouter from "./push-notifications.js";
import groupChatsRouter from "./group-chats.js";
import paymeRouter from "./payme.js";
import paynetRouter from "./paynet.js";
import blockedAppsRouter from "./blocked-apps.js";
import reportsRouter from "./reports.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth",       authRouter);
router.use("/rides",      ridesRouter);
router.use("/drivers",    driversRouter);
router.use("/dispatcher", dispatcherRouter);
router.use("/rides",      messagesRouter);
router.use("/tariffs",    tariffsRouter);
router.use("/calls",      callsRouter);
router.use("/analytics",  analyticsRouter);
router.use("/payments",   paymentsRouter);
router.use("/routes",     routesMgmtRouter);
router.use("/route-options", routeOptionsRouter);
router.use("/branches",   branchesRouter);
router.use("/cities",     citiesRouter);
router.use("/addresses",  addressesRouter);
router.use("/districts",  districtsRouter);
router.use("/staff",      staffRouter);
router.use("/settings",   settingsRouter);
router.use("/activity-logs", activityLogsRouter);
router.use("/chat",       chatRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/metrics", metricsRouter);
router.use("/rbac", rbacRouter);
router.use("/driver-groups", driverGroupsRouter);
router.use("/photo-control", photoControlRouter);
router.use("/audio-files", audioFilesRouter);
router.use("/system", systemRouter);
router.use("/debug", debugRouter);
router.use(apkRouter);
router.use("/news", newsRouter);
router.use("/push-notifications", pushNotificationsRouter);
router.use("/group-chats", groupChatsRouter);
router.use("/payme", paymeRouter);
router.use("/paynet", paynetRouter);
router.use("/blocked-apps", blockedAppsRouter);
router.use("/reports", reportsRouter);

export default router;
